# Site
title:              /var/log/機械学習.gz
bio:                'Nullius in verba.'
description:        "Nullius in verba."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/kizuna_akari.png'
background:         'assets/img/yukari.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ja_JP
url:                https://gink03.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   nardtree

#email:
twitter:            nardtree
#facebook:           username
github-url:         GINK03
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
tumblr:             nardtree-catindog
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:            gimpei03
#youtube-channel:   channel
soundcloud:         sgemuj01eczp
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

theme: jekyll-theme-cayman
